export const columns = [
  { key: "category", label: "Category" },
  { key: "openSource", label: "Open Source" },
  { key: "aws", label: "AWS" },
  { key: "azure", label: "Microsoft Azure" },
  { key: "fabric", label: "Microsoft Fabric Services" },
  { key: "gcp", label: "GCP" },
  { key: "cloudera", label: "Cloudera" },
  { key: "databricks", label: "Databricks" },
];

export const categories = [
  {
    category: "Workflow Orchestration",
    openSource: "Apache Airflow",
    aws: "Step Functions, MWAA (Managed Airflow)",
    azure: "Data Factory (Pipelines), Synapse Pipelines",
    fabric: "Data Factory (Data Pipelines)",
    gcp: "Cloud Composer (Airflow)",
    cloudera: "Apache Airflow, Oozie",
    databricks: "Workflows & Jobs",
  },
  {
    category: "Streaming & Event Ingestion",
    openSource: "Apache Kafka, Apache Flink",
    aws: "Kinesis, MSK",
    azure: "Event Hubs",
    fabric:
      "Real-Time Intelligence (Eventstreams, Eventhouse, KQL DB), Event Hubs",
    gcp: "Pub/Sub, Dataflow",
    cloudera: "Kafka, Flink",
    databricks: "Autoloader, Structured Streaming, Delta Live Tables",
  },
  {
    category: "Batch Data Ingestion",
    openSource: "Apache NiFi, Sqoop",
    aws: "Glue ETL, DMS (Database Migration Service)",
    azure: "Azure Data Factory, ADLS Gen2",
    fabric: "Dataflow, Data Pipelines (Copy, Mapping Dataflows)",
    gcp: "Cloud Storage Transfer, Dataflow",
    cloudera: "HDFS, NiFi, Sqoop",
    databricks: "Autoloader, Delta Lake",
  },
  {
    category: "Data Transformation (Code-based)",
    openSource: "Apache Spark, Python/Pandas",
    aws: "Glue ETL (PySpark), Lambda",
    azure: "Synapse Spark Pools, Azure Databricks",
    fabric: "Data Engineering (Spark, Notebooks), Dataflows",
    gcp: "Dataproc, Dataflow (Spark)",
    cloudera: "Spark, Flink",
    databricks: "Databricks Spark, Delta Live Tables",
  },
  {
    category: "Data Transformation (SQL / Declarative)",
    openSource: "Apache Hive, Presto/Trino",
    aws: "Athena, Redshift Spectrum",
    azure: "Synapse SQL Pools, Azure Data Explorer",
    fabric: "SQL Endpoint (Lakehouse), Dataflows, Dataverse",
    gcp: "BigQuery, Dataform",
    cloudera: "Hive, Impala",
    databricks: "Databricks SQL, Delta Engine",
  },
  {
    category: "Data Quality & Testing",
    openSource: "Great Expectations, Deequ",
    aws: "Glue DataBrew, Deequ",
    azure: "Data Quality Services, Purview",
    fabric: "Purview Data Quality, Data Activator",
    gcp: "Cloud DLP, Dataplex (quality rules)",
    cloudera: "Atlas, SDX, Navigator",
    databricks: "Unity Catalog (DQ policies), Great Expectations",
  },
  {
    category: "Data Catalog & Lineage",
    openSource: "Apache Atlas, Amundsen",
    aws: "Glue Data Catalog, Lake Formation",
    azure: "Purview",
    fabric: "Purview (governance & lineage)",
    gcp: "Data Catalog",
    cloudera: "Cloudera Data Catalog",
    databricks: "Unity Catalog",
  },
  {
    category: "Object / File Storage (Data Lake)",
    openSource: "HDFS, MinIO",
    aws: "S3",
    azure: "ADLS Gen2",
    fabric: "OneLake (Fabric Lakehouse)",
    gcp: "Cloud Storage",
    cloudera: "HDFS",
    databricks: "Delta Lake (DBFS)",
  },
  {
    category: "Warehouse / Query Engine",
    openSource: "Presto, Trino, Hive LLAP",
    aws: "Redshift, Athena",
    azure: "Synapse Analytics",
    fabric: "SQL Endpoint (Lakehouse), Dataverse, Power BI Direct Lake",
    gcp: "BigQuery",
    cloudera: "Impala, Hive",
    databricks: "Databricks SQL, Photon Engine",
  },
  {
    category: "NoSQL / Real-Time Database",
    openSource: "Apache Cassandra, MongoDB, Redis",
    aws: "DynamoDB, ElastiCache",
    azure: "Cosmos DB",
    fabric: "KQL Database, Eventhouse",
    gcp: "Firestore, Cloud Spanner",
    cloudera: "Apache Kudu",
    databricks: "(N/A — Lakehouse focus, no native NoSQL)",
  },
  {
    category: "Machine Learning / AI",
    openSource: "TensorFlow, PyTorch, Scikit-learn, MLflow",
    aws: "SageMaker, Rekognition, Bedrock",
    azure: "Azure ML, Cognitive Services",
    fabric: "Fabric ML (integrated with Azure ML)",
    gcp: "Vertex AI, AutoML",
    cloudera: "Spark MLlib, CDSW (Cloudera Data Science Workbench)",
    databricks: "Databricks MLflow, Feature Store",
  },
  {
    category: "Data Visualization / BI",
    openSource: "Superset, Grafana, Metabase",
    aws: "QuickSight",
    azure: "Power BI",
    fabric: "Power BI (Direct Lake, Embedded)",
    gcp: "Looker, Data Studio",
    cloudera: "Cloudera Data Visualization",
    databricks: "Databricks SQL Dashboards",
  },
  {
    category: "Security & Access Control",
    openSource: "Apache Ranger, Kerberos",
    aws: "IAM, Lake Formation, KMS",
    azure: "Entra ID (AAD), Purview, Key Vault",
    fabric: "Purview + Entra ID + Fabric Security Policies",
    gcp: "Cloud IAM, Cloud DLP",
    cloudera: "Ranger, Sentry, SDX",
    databricks: "Unity Catalog (RBAC + Policies)",
  },
  {
    category: "Monitoring & Observability",
    openSource: "Prometheus, Grafana, ELK Stack",
    aws: "CloudWatch, X-Ray",
    azure: "Azure Monitor, Log Analytics, App Insights",
    fabric: "Fabric Monitoring (Activity Hub, Logs, KQL)",
    gcp: "Cloud Monitoring, Logging, Error Reporting",
    cloudera: "Cloudera Manager, Workload XM",
    databricks: "System Tables, Audit Logs, Metrics API",
  },
];
